name: Scrape Annabelle Institut
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Dependencies
        run: npm install
      - name: Install Puppeteer Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libx11-xcb1 libxcb1 libxcomposite1 libxi6 libxtst6 libnss3 libpangocairo-1.0-0
      - name: Run Scraper
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: node scraper.js
      - name: Commit Results
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          if git status --porcelain | grep -q .; then
            git commit -m "Add new scrape results - $(date '+%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
